TRUNCATE TABLE attraction CASCADE;

TRUNCATE TABLE attraction_type CASCADE;

TRUNCATE TABLE client CASCADE;

TRUNCATE TABLE days CASCADE;

TRUNCATE TABLE daytime CASCADE;

TRUNCATE TABLE disc_group CASCADE;

TRUNCATE TABLE history CASCADE;

TRUNCATE TABLE pass CASCADE;

TRUNCATE TABLE pass_prc_lst CASCADE;

TRUNCATE TABLE pass_prc_lst_pos CASCADE;

TRUNCATE TABLE pass_type CASCADE;

TRUNCATE TABLE tckt_prc_lst CASCADE;

TRUNCATE TABLE tckt_prc_lst_pos CASCADE;

TRUNCATE TABLE ticket CASCADE;

TRUNCATE TABLE watch CASCADE;